#!/usr/bin/env python
from sys import stderr, argv
from lib.actions import *
from lib.proto import Proto
from lib.storage import del_card
from lib.password import get_token
import argparse
if __name__ == '__main__':
  url = argv[1] if len(argv) > 1 else None
  token = get_token()
  proto = Proto(url)
  print 'Please swipe token'
  card = scan(token, proto=proto)
  assert(card.command == 'S')
  status = revoke_mid(token, card.mid, proto=proto)
  if status.command == 'K':
      (uid, name) = del_card(card.mid)
      print 'Card %x (user %s, uid %d) revoked' % (card.mid, name, card.uid)
  else:
      print >> stderr, 'Unknown error:', str(status)
      exit(1)
