#!/usr/bin/env python
from sys import stderr, argv
from lib.actions import *
from lib.storage import del_uid
from lib.password import get_token
import argparse
if __name__ == '__main__':
  url = argv[2] if len(argv) > 2 else None
  token = get_token()
  uid = int(argv[1])
  status = revoke_uid(token, uid)
  if status.command == 'K':
      del_uid(uid)
      print 'User %d revoked' % uid
  else:
      print >> stderr, 'Unknown error:', status
      exit(1)
