#!/usr/bin/env python

import argparse
from sys import stderr, argv

from lib.actions import *
from lib.proto import Proto
from lib.storage import cards_for_user, del_card
from lib.password import get_token

if __name__ == '__main__':
    url = argv[2] if len(argv) > 2 else None
    token = get_token()
    proto = Proto(url)
    user = argv[1]
    cards = cards_for_user(user)
    for h in cards:
        print 'Revoking card %s' % h
        status = revoke_hash(token, h, proto=proto)
        if status.command == 'K':
            del_card(h)
            print 'Card %s revoked' % h
        else:
            print >> stderr, 'Unknown error:', status
            exit(1)
    print 'User %s\'s cards revoked' % user
