#!/usr/bin/env python2

from sys import argv

from lib.actions import scan
from lib.proto import Proto
from lib.storage import get_card
from lib.password import get_token
import options

if __name__ == '__main__':
    url = argv[1] if len(argv) > 1 else options.url
    token = get_token()
    proto = Proto(url)
    print 'Please swipe token'
    c = scan(token, proto=proto)
    assert(c.command.upper() == 'S')
    print 'Hash: %s, UID: %x, Username: %s' % \
        (c.hash, c.uid, get_card(c.hash)[1])
