#!/usr/bin/env python

from sys import argv

from lib.actions import scan
from lib.proto import Proto
from lib.storage import get_card
from lib.password import get_token

if __name__ == '__main__':
    url = argv[1] if len(argv) > 1 else None
    token = get_token()
    proto = Proto(url)
    print 'Please swipe token'
    c = scan(token, proto=proto)
    assert(c.command == 'S')
    print 'CardID: %x, UID: %x, Username: %s' % \
        (c.mid, c.uid, get_card(c.mid)[1])
