#!/usr/bin/env python

import argparse
from sys import stderr, argv

from lib.actions import *
from lib.proto import Proto
from lib.storage import del_card
from lib.password import get_token

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Revoke a single card')
    parser.add_argument('url', 
        help='Serial connection to use',
        default=options.url,
        nargs='?')
    parser.add_argument('-l', '--local', action='store_true',
        help='If specified, only update local base',)
    parser.add_argument('-c', '--card', help='Card+PIN hash (will not scan), only required with -l')
    args = parser.parse_args()
    if args.local and not args.card:
        print 'Local update requires a card to be specified!'
        exit(2)
    card = args.card
    if not args.local:
        token = get_token()
        proto = Proto(args.url)
        if not args.card:
            print 'Please swipe token'
            frame = scan(token, proto=proto)
            assert(frame.command == 'S')
            card = frame.hash
        status = revoke_mid(token, card, proto=proto)
        if status.command != 'K':
            print >> stderr, 'Unknown error:', str(status)
            exit(1)
    (uid, name) = del_card(card)
    print 'Card %x (user %s, uid %d) revoked' % (card, name, uid)
