#!/usr/bin/env python2

from sys import argv

from lib.actions import scan
from lib.proto import Proto
from lib.storage import get_card
from lib.password import get_token
from lib.command import signed_command
import options

if __name__ == '__main__':
    url = argv[1] if len(argv) > 1 else options.url
    token = get_token()
    proto = Proto(url)
    proto.send(signed_command(command='P', hash=options.empty_hash, uid=0, token=token))
    while True:
        print proto.fd.readline(),
