#!/usr/bin/env python

import argparse
import options
from sys import stderr, argv

from lib.actions import *
from lib.proto import Proto
from lib.storage import cards_for_user, del_card
from lib.password import get_token

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Revoke all cards for a single user')
    parser.add_argument('name',
        help='User whose cards will be revoked')
    parser.add_argument('url', 
        help='Serial connection to use', 
        default=options.url,
        nargs='?')
    parser.add_argument('-l', '--local', action='store_true',
        help='If specified, only update local base',)
    args = parser.parse_args()
    user = args.name
    cards = cards_for_user(user)
    if args.local:
        for h in cards:
            del_card(h)
            print 'Card %s revoked' % h
    else:
        token = get_token()
        proto = Proto(url)
        user = argv[1]
        for h in cards:
            print 'Revoking card %s' % h
            status = revoke_hash(token, h, proto=proto)
            if status.command == 'K':
                del_card(h)
                print 'Card %s revoked' % h
            else:
                print >> stderr, 'Unknown error:', status
                exit(1)
    print 'User %s\'s cards revoked' % user
